### ISSUE TITLE
TEST - Automated sanity testing

### ISSUE THREAD

**Issue by Noabsa** [nabsa-me/Workshops#12]
**Source**
https://blog.gopenai.com/testing-under-pressure-how-we-built-an-autonomous-testing-framework-20ce37c9fc53

**Tasks**
- [ ] Check testing frameworks, choose the next to develope
- [ ] Research about automated testing
- [ ] Research about sanity testing layer
- [ ] Plan the integration in project (naBit or gooDo)
